version: 2
jobs:
  # Semantic release
  analyze_tag_release:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules/
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Semantic release
          command: yarn release

  # Build and deploy iOS and Android
  build_ios:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Building iOS
          command: echo "Building iOS"

  # Build and deploy iOS and Android
  build_android:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Building Android
          command: echo "Building Android"

  # Build and deploy iOS and Android
  deploy_ios:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Deploy iOS
          command: echo "Deploy iOS"

  # Build and deploy iOS and Android
  deploy_android:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Deploy iOS
          command: echo "Deploy Android"

  # Verify repo and unit test
  verify_unit_tests:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Unit tests
          command: echo "Run unit tests"

workflows:
  version: 2

  # Trigger workflow for last commit (merge commits) to master
  # Run unit tests for sanity and if all looks good run semantic release
  # Semantic release will decide based on commit messages if another release is needed
  # Ignore all tags
  semantic-release:
    jobs:
      - verify_unit_tests:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
      - analyze_tag_release:
          requires:
            - verify_unit_tests
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/

  # This gets triggers on every push to all branches except master
  # It verifies the branch, runs unit tests and builds iOS and Android
  verify-test-build:
    jobs:
      - verify_unit_tests:
          filters:
            branches:
              ignore:
                - master
      - build_ios:
          requires:
            - verify_unit_tests
          filters:
            branches:
              ignore:
                - master
      - build_android:
          requires:
            - verify_unit_tests
          filters:
            branches:
              ignore:
                - master

  tag-build-deploy-release:
    jobs:
      - verify_unit_tests:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build_ios:
          requires:
            - verify_unit_tests
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build_android:
          requires:
            - verify_unit_tests
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_ios:
          requires:
            - verify_unit_tests
            - build_ios
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_android:
          requires:
            - verify_unit_tests
            - build_android
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
