version: 2
jobs:
  new_release:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules/
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Semantic release
          command: yarn release
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  deploy_new_version:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Run command
          command: echo "Deploying new version"

  verify_unit_tests:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install node modules
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules/
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Unit tests
          command: yarn test --maxWorkers=2
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

workflows:
  version: 2

  increment_version:
    jobs:
      - new_release:
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /^v.*/

  test_build:
    jobs:
      - verify_unit_tests:
          filters:
            branches:
              ignore:
                - master

  test_build_deploy:
    jobs:
      - verify_unit_tests:
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - deploy_new_version:
          requires:
            - verify_unit_tests
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
